### PR TITLE
Geometryclass

### PR DESCRIPTION
**Pull request by bnel1201**
Hi @AnderBiguri  and @ashwinpn,

Is there still interest in this from [#146](https://github.com/CERN/TIGRE/issues/146)? I've added an interface which sets an agreement on the required fields and then new geometries can be subclassed from that. I turned defaultGeometry, which was a function before, into an example subclass. This doesn't change any functionality, and didnt break in going through the demos or my code, but it opens up the possibility to have different behavior depending on the geometry type. This can be helpful in removing if-else statements.

### CODE REVIEW

**Comment by AnderBiguri** [comment]
Ah this is great! If you are interested, this is indeed something that can lead to a lot of code removal in TIGRE (which is great!).

Sounds like a good thing, and I haven't really heard from @ashwinpn, so its good if you want to tackle this. 
Just a word of advise, I can definetly test and review, advise, guide, comment and test on this, but I won't be able to get my hands very dirty with the code, so if you want to proper tackle this, then it will be on you ;) 

If you are cool with that, then this can be a great idea. It can help remove all the ugly aux variables such as the "alpha_blocks" and indexes on SART type minimization (e.g. https://github.com/CERN/TIGRE/blob/master/MATLAB/Algorithms/OS_SART.m#L86)  or all the ugly if chunks like https://github.com/CERN/TIGRE/blob/master/MATLAB/Algorithms/OS_SART.m#L136-L152. Do let me know if you want to tackle it and if you want any advise on where to start! 

And please feel free to send me an email if thre anything to discuss that may be too long for Github (I am happy to keep the conversations here too :) )

**Comment by bnel1201** [comment]
Sounds good! I'll push forward on this and will let you know when I need assistance.

**Comment by AnderBiguri** [comment]
I will go adding TODOs into https://github.com/CERN/TIGRE/projects/3

**Comment by bnel1201** [comment]
Very good. For the first card, the short-term solution is to spit out class properties into a struct so as to be compatible with the MATLAB C API. I'll bet the C++ API can handle classes but that would be more of a rewrite and people would have to recompile.

I'll start on the MATLAB side, using more OOP language features can clean up those variables you mentioned. For more specific details I'll follow up with email but I wanted to put the game plan on GitHub.

**Comment by AnderBiguri** [comment]
@bnel1201 sounds good! Feel free to add anything to the project, just created them so we can keep better track of what may be missing :)

**Comment by AnderBiguri** [comment]
This looks dead now. I will close it, but if anyone is interested in reviving it, let me know and I will reopen it :) 

Thanks for the work anyway!

**Pull request closed without merging**
