### PR TITLE
Fix minor bugs in Python version

### PR DESCRIPTION
**Pull request by yliu88au**
Fix some minor bugs for Python version (Windows)

### CODE REVIEW

**Comment by yliu88au** [comment]
Need more check

**Comment by yliu88au** [comment]
I think install it in Windows needs these dll lines. Perhaps we can test OS platform using:
import sys
if sys.platform='wins':
    dll lines

I can test it tomorrow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AnderBiguri** [comment]
@yliu88au I am not entirely sure they are needed. Some discussion in #576

**Comment by yliu88au** [comment]
perhaps because I used
pip install cupy-cuda12x
in the same virtual environment, my cuda version is 12.6.3, I think.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
