### PR TITLE
Fixed Python plotImg and plotProj functions

### PR DESCRIPTION
**Pull request by genusn**
## Summary
 * plotImg and plotProj become to show consistent images
 * Added function to save as gif
 * plotimg is fixed and renamed to plotImg.
 * plotproj is rewitten to plotProj, based on plotImg

#### test_plotImg.py
```
#%%
# Init
import copy
import numpy as np
import time
import sys
import collections
from matplotlib import pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

import tigre
import tigre.algorithms as algs
from tigre.demos.Test_data import data_loader
from tigre.utilities.Measure_Quality import Measure_Quality

nangles=30
nVoxelX=256
nVoxelY=128
nVoxelZ=64
nDetectorU=250
nDetectorV=125

geo=tigre.geometry(mode='cone', nVoxel=np.array([nVoxelZ,nVoxelY,nVoxelX]), default=True)
geo.nDetector=np.array([nDetectorV, nDetectorU])
geo.dDetector=np.array([0.8, 0.8])*5 	
geo.sDetector=geo.nDetector *geo.dDetector

#%%
angles=np.linspace(0, 2 * np.pi, nangles, dtype=np.float32)
head=data_loader.load_head_phantom(geo.nVoxel)
print(head.shape)
#%%
# Draw 3 bars along axes from origin toward + directions.

muBar = 1
head[nVoxelZ*2//4   : nVoxelZ*3//4+1
   , nVoxelY*2//4-5 : nVoxelY*2//4+5 
   , nVoxelX*2//4-5 : nVoxelX*2//4+5] = muBar

head[nVoxelZ*2//4-5 : nVoxelZ*2//4+5 
   , nVoxelY*2//4   : nVoxelY*3//4   
   , nVoxelX*2//4-5 : nVoxelX*2//4+5] = muBar

head[nVoxelZ*2//4-5 : nVoxelZ*2//4+5 
   , nVoxelY*2//4-5 : nVoxelY*2//4+5 
   , nVoxelX*2//4   : nVoxelX*3//4  ] = muBar

#%% plot
tigre.plotimg(head, step=10)
tigre.plotImg(head, dim='X', step=10, savegif='plotImg_dim1.gif')
tigre.plotImg(head, dim='Y', step=10, savegif='plotImg_dim2.gif')
tigre.plotImg(head, dim='Z', step=10, savegif='plotImg_dim3.gif')
tigre.plotImg(head, dim='x', step=10)
tigre.plotImg(head, dim='y', step=10)
tigre.plotImg(head, dim='Z', step=10)


print("slice")

tigre.plotImg(head, dim='X', slice=128)
tigre.plotImg(head, dim='Y', slice=67)
tigre.plotImg(head, dim='Z', slice=30)
```

* plotImg_dim3.gif

plotImg_dim3

### test_plotProj.py
```
#%%
# Init
import copy
import numpy as np
import time
import sys
import collections
from matplotlib import pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

import tigre
import tigre.algorithms as algs
from tigre.demos.Test_data import data_loader
from tigre.utilities.Measure_Quality import Measure_Quality

nangles=30
nVoxelX=256
nVoxelY=128
nVoxelZ=64
nDetectorU=250
nDetectorV=125

geo=tigre.geometry(mode='cone', nVoxel=np.array([nVoxelZ,nVoxelY,nVoxelX]), default=True)
geo.nDetector=np.array([nDetectorV, nDetectorU])
geo.dDetector=np.array([0.8, 0.8])*5 
geo.sDetector=geo.nDetector *geo.dDetector

#%%
angles=np.linspace(0, 2 * np.pi, nangles, dtype=np.float32)
head=data_loader.load_head_phantom(geo.nVoxel)
print(head.shape)
#%%
# Draw 3 bars along axes from origin toward + directions.

muBar = 1
head[nVoxelZ*2//4   : nVoxelZ*3//4+1
   , nVoxelY*2//4-5 : nVoxelY*2//4+5 
   , nVoxelX*2//4-5 : nVoxelX*2//4+5] = muBar

head[nVoxelZ*2//4-5 : nVoxelZ*2//4+5 
   , nVoxelY*2//4   : nVoxelY*3//4   
   , nVoxelX*2//4-5 : nVoxelX*2//4+5] = muBar

head[nVoxelZ*2//4-5 : nVoxelZ*2//4+5 
   , nVoxelY*2//4-5 : nVoxelY*2//4+5 
   , nVoxelX*2//4   : nVoxelX*3//4  ] = muBar

#%%
# Project and draw point in the 1st quadrant.
proj = tigre.Ax(head,geo,angles,'interpolated')
maxVal=np.max(proj)
print(maxVal)

proj[:, nDetectorV*3//4-5:nDetectorV*3//4+5, nDetectorU*3//4-5:nDetectorU*3//4+5]=maxVal


# %%
# Plot
print("proj shape = {}".format(proj.shape))
tigre.plotProj(proj)           # projection
tigre.plotProj(proj, angles=angles)           # projection
tigre.plotProj(proj, dim='u')  # ?
tigre.plotProj(proj, dim='v')    # sinogram

tigre.plotProj(proj, dim='U', step=10, savegif='plotProj_dim1.gif')
tigre.plotProj(proj, dim='V', step=10, savegif='plotProj_dim2.gif')
tigre.plotProj(proj, dim='T', step=10, savegif='plotProj_dim3.gif')
tigre.plotProj(proj, dim='u', step=10)
tigre.plotProj(proj, dim='v', step=10)
tigre.plotProj(proj, dim='t', step=10)

# print("slice")

tigre.plotProj(proj, dim='U', slice=nDetectorU*2//4)
tigre.plotProj(proj, dim='V', slice=nDetectorV*3//4)
tigre.plotProj(proj, dim='T', slice=nangles//2+1)
tigre.plotProj(proj, dim='T', slice=nangles//2, angles=angles)

tigre.plotSinogram(proj, 14)
```

 * plotProj_dim2.gif
plotProj_dim2

 * plotProj_dim3.gif
plotProj_dim3

### CODE REVIEW

**Comment by AnderBiguri** [comment]
Fantastic, as usual. I'll read a bit the code, but if we are renaming the functions, maybe we should stick with python conventions, i.e. using `snake_case` instead of `camelCase`? So calling the functions `plot_img` and `plot_proj` ? What do you think?

**Comment by genusn** [comment]
In fact, I have never cared about PEP...  No problem. Shall I or could you?

**Comment by AnderBiguri** [comment]
@genusn as you wish, easier for me if you do it, but if you prefer I can do it :)

**Comment by genusn** [comment]
@AnderBiguri I would like to ask you this time. Thank you very much.

**Comment by AnderBiguri** [comment]
@genusn grea,t I'll do it then! I'll merge the PR, maybe tackle anything PEP related later in the progress of your work :) I'll open an issue.

**Pull request merged**
