### PR TITLE
small bug fix

### PR DESCRIPTION
**Pull request by yliu88au**
Fix a small bug in minimizeAwTV.m

### CODE REVIEW

**Comment by AnderBiguri** [comment]
Hi! Thanks, this looks good. 

The problem is that the file is in a different location, thus if I "merge" it now, we will have duplicate files. 
You can try to change that in your local files, or otherwise, I will do it, no worries :)

**Comment by AnderBiguri** [comment]
You have now added all MATLAB files into the main folder, which would duplicate all the files. 
(take your time to fix these things if you want, git/github is hard if you are not used to it :) )

**Comment by yliu88au** [comment]
Yes, I am totally confused!

**Comment by AnderBiguri** [comment]
I will cancel this pull request, so you have time to tidy. 

The general idea is to make a branch (like in the other PR) and within your computer, change your local "master" to the branch, and then just modify the files on place, and commit them.

If this is a headache, just send me the files, and I'll try to do it :)

**Comment by yliu88au** [comment]
You can do it. 😊 There is a small mod on FDK to remove toolbox dependency (range()).

Yes, for MLEM default initial image should be ones. I am still totally confused about github.

Regards,
Yi

**Comment by AnderBiguri** [comment]
Hi Yi,

This is the PR #205, However, you added those things you mention into PR #206, which is actually really good and tidy. 
I'd be very happy to help tidy that one up if you want, but that will mean that I will change your Github repository, to match TIGRE and tidy everything there before merging it to TIGRE.

Is it OK if I do that? I don't want to modify your code without permission

**Comment by yliu88au** [comment]
Yes, go ahead please.

**Pull request closed without merging**
