### PR TITLE
Fix cython3 issues

### LINKED ISSUE #471: Python 3.10 install error:file tigre\py.py (for module tigre.py) not found
## Expected Behavior
When I run `python ./setup.py install`, it returns error:

running install
D:\miniconda3\envs\cil\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\miniconda3\envs\cil\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing pytigre.egg-info\PKG-INFO
writing dependency_links to pytigre.egg-info\dependency_links.txt
writing requirements to pytigre.egg-info\requires.txt
writing top-level names to pytigre.egg-info\top_level.txt
file tigre\py.py (for module tigre.py) not found
reading manifest file 'pytigre.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.ipynb' under directory 'tigre\demos'
warning: no files found matching '*.mat' under directory 'tigre\demos'
adding license  file 'LICENSE'
writing manifest file 'pytigre.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
file tigre\py.py (for module tigre.py) not found
D:\miniconda3\envs\cil\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'tigre.utilities.cuda_interface' as data is deprecated, please list it in `packages`.
    !!
    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'tigre.utilities.cuda_interface' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'tigre.utilities.cuda_interface' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'tigre.utilities.cuda_interface' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.
!!

  check.warn(importable)
 **file tigre\py.py (for module tigre.py) not found**
running build_ext
building '_Ax' extension
error: unknown file type '.pxd' (from 'tigre/utilities/cuda_interface/_gpuUtils.pxd')

## Actual Behavior
I don't find the py.py in tigre file. How can I fix it. Thank you very much.

## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - python version: 3.10
  - OS:win10
  - CUDA version:CUDA 11.7

### PR DESCRIPTION
**Pull request by tsadakane**
# Purpose
Fix #471, #472, #473

# Test
## Environment
* OS: Windows 10 x64
* Python: Anaconda3
  * Python 3.11.4
  * Cython 3.0.0
  * numpy 1.25.2
* Visual Studio 2022
* CUDA 11.8
* GPU: 1x NVIDIA GeForce GTX 1060 6GB
## Steps
1. Compilation
```
> Python setup.py develop --user > Build.log 2>&1
```
2. Run a program
```
> python example.py
```
## Result
1. Compilation succeeded
2. Running `example.py` succeeded. (The xyz plots are displayed.)

### CODE REVIEW

**Comment by AnderBiguri** [comment]
Great! thanks a lot!

Have you tried installing with `python setup.py install` only?

**Comment by tsadakane** [comment]
The commands below worked fine:
```
> conda create -n test311 python=3.11
> conda install jupyter numpy matplotlib opencv pillow pandas scipy imageio cython pylint
> python setup.py install > Build.log 2>&1
> python example.py
```

One thing I realized is...
before installation, I could not find "pytigre" in the output of "pip list", and after installation, I found two "pytigre" lines.

 
image

**Comment by AnderBiguri** [comment]
Thanks for stepping in on this @tsadakane , super appreciated

**Comment by AnderBiguri** [comment]
@tsadakane its strange, the 2 lines, but I am not sure f this is from our side or something conda/setuptools. 
We can investigate further, but I am merging because ti solves a critical issue right know. Thanks again.

**Comment by tsadakane** [comment]
I tried with master@HEAD + Python 3.9 + Cython 0.29.
```
 > conda create -n test39 python=3.9
 > conda activate test39
 > conda install jupyter numpy matplotlib opencv pillow pandas scipy imageio cython==0.29.36 pylint 
 > pip list > pip_list_39.txt
 > python setup.py install > Build.log 2>&1
 > pip list > pip_list_39_after.txt
 > python example.py
```
After installation, "pip list" output contains only one "pytigre", with "Editable project location" field. Here is a portion of `pip_list_39_after.txt`
```
python-json-logger    2.0.7
pytigre               2.4.0     c:\opt\anaconda3\envs\test39\lib\site-packages\pytigre-2.4.0-py3.9-win-amd64.egg
pytz                  2022.7
```

**Comment by AnderBiguri** [comment]
@tsadakane it may have to do with the fact that installing via `python setup.py` is technically deprecated. I think the correct way is `pip install . ` now, but last time I tried that failed.

**Comment by tsadakane** [comment]
@AnderBiguri , I have succeeded `pip install -e .` with some modification, and I have just checked "pip list": The result contained only one "pytigre" line.
```
python-json-logger    2.0.7
pytigre               2.4.0
pytz                  2022.7
```

**Comment by AnderBiguri** [comment]
@tsadakane  great! I think a next step for TIGRE should be making that the default, and updating the docs. I am away from tomorrow, but if you can make a PR with the code, I'd be happy to update the docs on my way back and merge it :)

**Pull request merged**
