### PR TITLE
Selecting GPUs for CUDA code to run on

### PR DESCRIPTION
**Pull request by genusn**
A solution to #203.

User can select GPUs for CUDA code to run on.

As explained in Python/tests/list_gpu.py and MATLAB/Demos/d22_ListGPUs.m,
if you have only one type of GPUs installed, you don't have to change your code at all.
If you have multiple types of GPUs, two for GPGPU and one for video-output for example, passing  a ```GpuIds```  object to the algorithm or utilities function, you can make your code use only the specified GPUs.

Matlab files are tested on demos d04, d06, d07, d08, d09, d20 modified for my environment, which are not included in this PR.
For Python, probably all algorithms are checked, but I am not sure.
All run without warning. Results looks consistent so far, but not checked rigorously.

#### Matlab
 * Machine A
 
| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10 64bit |
|**MATLAB**|  2016a |
|**CUDA**| 11.1 |
|**Visual Studio**| 2015|
|**GPU**| GTX1060 |

 * Machine B
 
| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10  64bit |
|**MATLAB**|  2016a |
|**CUDA**| 11.1|
|**Visual Studio**| 2015|
|**GPU**| 2xRTX2080, 1xGTX1070 |

#### Python
 * Machine A 
 
| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10  64bit |
|**Python(anaconda)**|  3.8.5 |
|**CUDA**| 11.1|
|**Visual Studio**| 2019 |
|**GPU**| GTX1060 |

 * Machine B

| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10  64bit |
|**Python(anaconda)**|  3.8.5 |
|**CUDA**| 11.1|
|**Visual Studio**| 2019 |
|**GPU**| 2xRTX2080Ti, 1xGTX1070 |

### CODE REVIEW

**Comment by AnderBiguri** [comment]
This is worderful (and tedious) work. Thousands of thanks. 

Comment: MATLAB/Compile.m will need those new files passed on all OS, not only win64

**Comment by genusn** [comment]
> Comment: MATLAB/Compile.m will need those new files passed on all OS, not only win64

@AnderBiguri  Thank you for your comment. Added in 1036f36, but not tested at all on environment other than wint64.

**Comment by AnderBiguri** [comment]
Seems to work well as far as I can test and all features one would hope for are also implemented. 
Amazing work really.

**Comment by genusn** [comment]
@AnderBiguri #249 seems to stem from this change.

|  SHA-1 |   |Converge? |
|---|---|---|
| ```c311c360662b6fd316efc37c5e36a727bdf8335b``` |  Before | Yes|
| ```ed8fe2b3fca95e572c1c4e85bc678eaf0c398d52``` |  After | No|

I've found that the treatment of default value in ```parse_inputs``` functions .m files are not working properly, I don't know this is related to #249 though.

Could you revert this merger? Or shall I make other PRs to fix them?

**Comment by AnderBiguri** [comment]
@genusn do you know what is wrong? Other algorithms seem to work well. 

Lets try to fix it now, I committed some things on top, will be hard to revert the merge. 
Happy to help if you find out what is wrong

**Comment by AnderBiguri** [comment]
This is the issue I think:

https://github.com/CERN/TIGRE/blob/9b2f5fba8f8322e9d26de495b5f2f034303e9525/MATLAB/Source/Atb_mex.cpp#L103-L109

should happen for nrhs==5 too. Maybe we just need to remove the `if`, as I assume not `Atb_mex` is always called with all parameters. 

https://github.com/CERN/TIGRE/blob/9b2f5fba8f8322e9d26de495b5f2f034303e9525/MATLAB/Source/Atb_mex.cpp#L79-L81

**Comment by AnderBiguri** [comment]
@genusn  fixed :)

**Comment by genusn** [comment]
@AnderBiguri 
> I've found that the treatment of default value in parse_inputs functions .m files.....

You have also fixed this in 4eca279. Thank you very much.

**Comment by AnderBiguri** [comment]
@genusn  have you tried this on a linux machine?

I am getting 
`MATLAB/Source/GpuIds.cpp:14:50: error: ‘nullptr’ was not declared in this scope`

which is weird because it was introduced in C++11 and I am using gcc 7.5.

Must be something wrong with the xml, but can't pinpoint it.

**Comment by genusn** [comment]
> @genusn have you tried this on a linux machine?

No, I have not. How about add ``` -Dnullptr=0``` option to ```gcc```?

**Comment by AnderBiguri** [comment]
That does the job! thanks! Could not find which was the right flag to toggle!

**Comment by AnderBiguri** [comment]
Hi @genusn, pinging you in this old thread as I don't have any other way to contact you. Would it be possible for you to send me an email so we can quickly chat?

**Pull request merged**
