### PR TITLE
Fixed tvdenoising on Multi-GPU

### PR DESCRIPTION
**Pull request by genusn**
## Summary
 * Fixed FISTA on Multi-GPU (#190)

## Details
 * ```slices_per_split``` are replaced with ```slices_per_split*image_size[0]*image_size[1]```  around
https://github.com/CERN/TIGRE/blob/aab042202159181ca666bb0b7a8fba5592478b51/MATLAB/Source/tvdenoising.cu#L498-L501
 * ```pixels_per_slice``` is introduced and replaces ```image_size[0]*image_size[1]``` 
 * The comment below is moved to a right place. https://github.com/CERN/TIGRE/blob/aab042202159181ca666bb0b7a8fba5592478b51/MATLAB/Source/tvdenoising.cu#L387

### Code 
```
clear;
close all;
geo=defaultGeometry('nVoxel',[128;128;128]);                     
angles=linspace(0,2*pi-2*pi/30,30);
head=headPhantom(geo.nVoxel);
projections=Ax(head,geo,angles,'interpolated');
nIter=20;
imgFDK = FDK(projections,geo,angles);
imgFISTA_default = FISTA(projections,geo,angles,nIter);
maxFista = max(imgFISTA_default(:));
imgFISTA_default = imgFISTA_default/maxFista;
%% Plot the top and bottom of the FOV
subplot(5,2,1), imshow(imgFDK(:,:,1), 'DisplayRange',[])
subplot(5,2,2), imshow(imgFISTA_default(:,:,1), 'DisplayRange',[])
subplot(5,2,3), imshow(imgFDK(:,:,geo.nVoxel(3)/2), 'DisplayRange',[])
subplot(5,2,4), imshow(imgFISTA_default(:,:,geo.nVoxel(3)/2), 'DisplayRange',[])
subplot(5,2,5), imshow(imgFDK(:,:,geo.nVoxel(3)), 'DisplayRange',[])
subplot(5,2,6), imshow(imgFISTA_default(:,:,geo.nVoxel(3)), 'DisplayRange',[])

subplot(5,2,7), imshow(squeeze(imgFDK(:,geo.nVoxel(2)/2,:)), 'DisplayRange',[])
subplot(5,2,8), imshow(squeeze(imgFISTA_default(:,geo.nVoxel(2)/2,:)), 'DisplayRange',[])

subplot(5,2,9), imshow(squeeze(imgFDK(geo.nVoxel(1)/2,:,:)), 'DisplayRange',[])
subplot(5,2,10), imshow(squeeze(imgFISTA_default(geo.nVoxel(1)/2,:,:)), 'DisplayRange',[])

%%
plotImg([imgFDK, imgFISTA_default])
%%
plotImg([imgFDK, imgFISTA_default], 'Dim','Z')
```
### Result
Left column: FDK
Right column: FISTA

1st row: bottom plane
2nd row: central plane
3rd row: top plane
4th row: Y-slice
5th row: X-slice

 * Base (aab0422), 2-GPU machine,
2GPU_Orig

 
 * Base (aab0422) and PR on 1-GPU machine, and PR on 2-GPU machine
2GPU_PR

### Test evironments 
| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10 |
|**MATLAB**|  2016a |
|**CUDA**| 10.1|
|**Visual Studio**| 2015|
|**GPU**| GTX1060 |

| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10 |
|**MATLAB**|  2016a |
|**CUDA**| 10.1|
|**Visual Studio**| 2015|
|**GPU**| 2 x RTX2080Ti |

## Discussion
 * The top plane of FISTA looks weird, but I think it is due to the automatic grayscale adjustment.
 * I also tried anisotropic case on Python, based on the branch genusn:dev_multi-gpu-python, this worked fine.
 * Tested only 1- and 2-GPU environments.
 * Other edge cases are not tested.

### CODE REVIEW

**Comment by AnderBiguri** [comment]
I think what looks weird is just FISTA being a complicated algorithm, SART-TV would test this too, but likely give better results (albeit slower).

I'll merge this because it's a crashing bug, if there are more things to fix in the future we'll tackle them later

**Comment by AnderBiguri** [comment]
@genusn I am planning to draft a new release version of TIGRE (nothing really consequential, as code is in master anyway, but good to have some fixed releases). Are you still working on adding more things? From my side, I think all mayor issues are gone.

**Comment by AnderBiguri** [comment]
@genusn  ah wait, I forgot about a couple. Sometimes (before) some parameters such as COR did not seem to be passed to the CUDA code from python (#143). I need to test those things.

**Comment by genusn** [comment]
> Are you still working on adding more things?

No I am not. I am interested in #143, but I have not started anything at all.

I think I should write something about #191, but I don't know where to write.

**Comment by AnderBiguri** [comment]
@genusn indeed #143 is interesting, as while for medical CT is not, its a fundamental variable for micro-CT, or any scanner that does rotate the sample instead of the machine. I am still confused why it happens, I have not been able to find where the values become zero. But maybe with the changes you made, it doesn't happen anymore. 

Similarly I guess we should test if other things, such as offsets, work properly in python. Standard circular CT may work fine, but often both medical and micro-CT machines have either intentional or mechanical offsets in the detectors that will need to be accounted for. 

About #191, write any thoughts you have there (or we can chat via email).

**Comment by genusn** [comment]
@AnderBiguri 
>  I am still confused why it happens, I have not been able to find where the values become zero.

https://github.com/CERN/TIGRE/blob/220935ae7a6a002d64ea95ed8b6f69baae2f9d21/Python/tigre/Source/_types.pxd#L154-L158

Sorry if misunderstood, but zero is still substituted in ```convert_to_c_geometry``` function and ```c_geom``` is passed to the functions defined in .cu files.

**Comment by AnderBiguri** [comment]
Sorry, talked without looking at the code! Then we just need to take the input data there

**Pull request merged**
