### PR TITLE
Resolve numerical issue on ray-voxel projection

### LINKED ISSUE #198: Ax (ray-voxel) produces defect lines with specific parameters
## Expected Behavior
interpolated

## Actual Behavior
If the components of dDetector are integers and at least one of nDetectorU and nDetectorV is (are) odd number(s), the result of Ax of "ray-voxel" has defect line(s).

rayvoxel

I compared the results of "ray-voxel" and "interpolated" and obtained the image as below:

diffabs

  - revision: 220935a

## Code to reproduce the problem (If applicable)

```
clear;
close all;

nangles=30;
nVoxelX=128;
nVoxelY=128;
nVoxelZ=128;
nDetectorU=251;  % virtical line of 'degee 0' at 251, not: 250
nDetectorV=251;  % horizontal line at 251,249, 125,.. not at 120,100,250
    
geo=defaultGeometry('nVoxel',[nVoxelX;nVoxelY;nVoxelZ]);
geo.nDetector=[nDetectorU; nDetectorV];
geo.dDetector = [1; 1]*2;  % 2 can be replaced with (maybe) any integer
geo.sDetector=geo.nDetector.*geo.dDetector;

angles=linspace(0,2*pi-2*pi/nangles,nangles);
head=headPhantom(geo.nVoxel);

proj_rayvoxel=Ax(head,geo,angles,'ray-voxel');
proj_interp  =Ax(head,geo,angles,'interpolated');

plotProj(proj_rayvoxel, angles, 'savegif', 'rayvoxel.gif') % Looks wrong
plotProj(proj_interp, angles, 'savegif', 'interpolated.gif')   % Looks correct
plotProj(abs(proj_rayvoxel-proj_interp), angles, 'savegif', 'diffabs.gif')
```

## Specifications 

  - MATLAB version: 2016a
  - OS: Windows 10
  - CUDA version: 10.1
  - GPU: 1 x GTX1060

 * This also occurs in Python.

### PR DESCRIPTION
**Pull request by AnderBiguri**
Fix #198

### CODE REVIEW

**Comment by genusn** [comment]
Unfortunately this PR is not working as expected on my machine: although the vertical line at 0-degree disappeared from "diffabs.gif" of #198, the horizontal line still remains.

diffabs

rayvoxel

I made a fresh clone and checked-out the branch, compile, inittigre, and ran the script of #198. I added a ```printf``` just above your modification and checked that the line is executed.

**Comment by AnderBiguri** [comment]
That's interesting. Using the same code you used at #198?

Can you try to remove a zero from the epsilon, making it bigger?
Its interesting, it works well on my GPU, not sure what could be different.

**Comment by genusn** [comment]
>Can you try to remove a zero from the epsilon, making it bigger?

Did not work.
I  also tried
```
    float epsilon_offset=0.01; // Manually tested. 
    printf("computeDeltas_Siddon(epsilon_offset = %f)\n", epsilon_offset);
```
, but the result was the same.

Here is my test code:
```
clear;
close all;

nangles=30;
nVoxelX=128;
nVoxelY=128;
nVoxelZ=128;
nDetectorU=251;  % virtical line of 'degee 0' at 251, not: 250
nDetectorV=251;  % horizontal line at 251,249, 125,.. not at 120,100,250
    
geo=defaultGeometry('nVoxel',[nVoxelX;nVoxelY;nVoxelZ]);
geo.nDetector=[nDetectorU; nDetectorV];
geo.dDetector = [1; 1]*2;  % 2 can be replaced with (maybe) any integer
geo.sDetector=geo.nDetector.*geo.dDetector;

angles=linspace(0,2*pi-2*pi/nangles,nangles);
head=headPhantom(geo.nVoxel);

proj_rayvoxel=Ax(head,geo,angles,'ray-voxel');
proj_interp  =Ax(head,geo,angles,'interpolated');

plotProj(proj_rayvoxel, angles, 'savegif', 'rayvoxel.gif') % Looks wrong
plotProj(proj_interp, angles, 'savegif', 'interpolated.gif')   % Looks correct
plotProj(abs(proj_rayvoxel-proj_interp), angles, 'savegif', 'diffabs.gif')
```

Because my MATLAB is 2016a, the compiler is Visual Studio 2015.

**Comment by AnderBiguri** [comment]
That is interesting, I can run this exact same code and it works. 
Are you running on 2 GPUs?

**Comment by genusn** [comment]
No, single GPU as mentioned in #198.

**Comment by AnderBiguri** [comment]
Hum, really no idea. I'll try on my other machine that has similar specs as your machine, see if I can reproduce it there... 
I could reproduce it before, but this code fixed it, its interesting that you still get it.

**Comment by genusn** [comment]
Really interesting....
I can try on my another machine which has 2-GPU, disabling one of two, but cannot do it this week.

**Comment by genusn** [comment]
Also on 2-GPU machine, this still occurred.
I modified as follows:
```
    float epsilon_offset=0.01; // Manually tested. 
    if(geo.nDetecU%2 && (!(geo.nVoxelX%2) || !(geo.nVoxelY%2)) && abs(geo.offDetecU[i])<=epsilon_offset){
        printf("off U %f\n", epsilon_offset);
        geo.offDetecU[i]=epsilon_offset;
    }
    if(geo.nDetecV%2 && !(geo.nVoxelZ%2) && abs(geo.offDetecV[i])==epsilon_offset) {
        printf("off V %f\n", epsilon_offset);
        geo.offDetecV[i]=epsilon_offset;
    }
```
Only "off U" lines were printed.

**Comment by AnderBiguri** [comment]
Ah, there was a typo, maybe thats the issue, as I can see the vertical lines are gone in your example. No idea why I was not getting it though. Its on the edge of numerical precision, so likely compiler optimization issue.

**Comment by genusn** [comment]
Worked fine on my machine!

**Pull request merged**
