### PR TITLE
Code Style Unification

### PR DESCRIPTION
**Pull request by sco1**
Per #194, this is a preview of opt-in code formatting & linting via black, flake8, and pre-commit.

#### Tooling introduced
  * [black](https://github.com/psf/black)
  * [flake8](https://flake8.pycqa.org/en/latest/)
  * [flake8-annotations](https://github.com/sco1/flake8-annotations)
  * [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear)
  * [flake8-docstrings](https://gitlab.com/pycqa/flake8-docstrings)
  * [flake8-import-order](https://github.com/PyCQA/flake8-import-order)
  * [pep8-naming](https://github.com/PyCQA/pep8-naming)
  * [pre-commit](https://pre-commit.com/)

#### TODO:
- [x] Tigre Base
	- [x] Algorithms
	- [x] Demos
	- [x] Utilities
- [x] Tests
- [ ] Check for regressions
- [ ] Dependency Spec
    - [x] Add optional linting requirements
    - [ ] Check installability

Based on the prevailing codestyle, enforcement on the existing code has been a bit selective. Naming and docstring conventions have been intentionally ignored in some places. A handful of changes made by black have also been manually reverted rather than refactored.

This unsurprisingly ends up being a fairly sizeable diff and, from experience with similar efforts in the past, will likely introduce merge conflicts with any existing branches/forks. Though easily resolved, it may be easier to just introduce the tooling without running it over the existing codebase and instead make incremental changes as time goes along rather than in one shot. Discussion on this point is welcome.

### CODE REVIEW

**Comment by AnderBiguri** [comment]
> Naming and docstring conventions have been intentionally ignored in some places. A handful of changes made by black have also been manually reverted rather than refactored.

TIGRE has been written without much style in mind, so I am happy to introduce changes for style that may break backwards compatibility. We'd need to tag the PR properly and perhaps delay it until a bit more of the WIP code is finished, but could work 

> This unsurprisingly ends up being a fairly sizeable diff and, from experience with similar efforts in the past, will likely introduce merge conflicts with any existing branches/forks. 

There are no python PRs/branches active, AFAIK.  Not at least from the TIGRE side. 

> Though easily resolved, it may be easier to just introduce the tooling without running it over the existing codebase and instead make incremental changes as time goes along rather than in one shot. Discussion on this point is welcome.

Mmm could be could be. I need to think a bit about it, as I'd like to have the code as tidy as possible (as its currently not very tidy), so I am tempted to just change a lot now, but have a good baseline for future code, instead of slowly changing everything. Mostly because not many people do PRs to TIGRE and those slow changes may become super slow.

What do you think?

**Comment by sco1** [comment]
> Mmm could be could be. I need to think a bit about it, as I'd like to have the code as tidy as possible (as its currently not very tidy), so I am tempted to just change a lot now, but have a good baseline for future code, instead of slowly changing everything

I only hesitate because it's realistically your burden being volunteered here to check against regressions once the big changes go beyond "no-op" changes to formatting. I haven't taken more than a quick glance at the test suite so I don't know how comprehensive it is, or how hands-on.

Given how big this diff is going to be already, I would want to keep this PR scoped more or less to formatting only to minimize the surface for regression. Perhaps finish off the linting, and then chunk up any potential rewrites (e.g. per-algorithm, utilities, etc.)?

**Comment by AnderBiguri** [comment]
I think that sounds good. Lets have the "one-off" standard linting etc in this one, and we can work later on the proper naming etc.

Admittedly, the testing is null. I think I may take some evenings soon and port all the MATLAB demos into python, which is as close to testing as TIGRE has.

**Comment by AnderBiguri** [comment]
Sorry, haven't tried it yet. 
A question: is there any instructions on how to opt in into the tools you provided via common editors? or will the files you added be picked automatically for style? 
If not, should we add some instructions so people can make PR following style?

**Comment by sco1** [comment]
No problem! I've been tied up with a similar effort on some code I inherited at work 😄 

I did forget to update the README but I have made a note to do so. I added a few avenues to accomplish the dev tools:

- Added the `lint` extra to `setup.py`, so a user should be able to do something like `pip install .[lint]` to install the extras. I don't currently have a working CUDA install so I haven't tried this one.
- Added a `requirements-dev.txt` with the same dependencies, so a user can do `pip install -r requirements-dev.txt`
- Pre-commit runs in its own environment using the specifications provided in `.pre-commit-config.yaml`, so once a user installs the hook then they're good to go

I'm not very familiar with automated discovery of these since I generally invoke linting manually or via pre-commit. I don't believe most tools will install them automatically, but should use them if installed in the project's environment.

**Comment by AnderBiguri** [comment]
Just tested this, all seems fine. 

I think it is missing 

- [ ] Solve merge conflicts
- [ ] Add tutorial/step by step instructions on how to use it (i.e. how to install it as you did, but also which command to use to run it). 

On that last note, I ran it on `-all-files` and I saw that it does change also the non-python code, but only for line ends etc. Is that something that is intentional/inbuilt into this PR, or should we make sure the instructions don't suggest it to run on all files?

**Comment by sco1** [comment]
Awesome, thanks for taking a look!

The hooks can specify [file and/or file type exclusions](https://pre-commit.com/#config-exclude), so we can ignore specific directories, name patterns, etc. Or we can just run it on Python files for now.

I should be able to work on the tutorial later this week or on the weekend.

**Comment by AnderBiguri** [comment]
Fantastic! No hurry of course, whenever you have time! 

I am happy if it works on other files too, as long as it does not try to impose some sort of pythonic style on C++/CUDA/MATLAB and just handles general stuff such as line ends etc.

**Comment by sco1** [comment]
Added some instructions to the Python README ([link](https://github.com/sco1/TIGRE/blob/code-style/Frontispiece/python_installation.md#optional-code-style-enforcement)) & resolved the conflicts!

**Comment by AnderBiguri** [comment]
Great! tested and happy with it. 

Are you happy to merge or do you want to do anything else?

**Comment by sco1** [comment]
Nothing I can think of in scope! As long as I didn't break anything 😁

**Pull request merged**
