### PR TITLE
Fix typo in docstring

### PR DESCRIPTION
**Pull request by genusn**
- lambdared => lmbda_red, lambda => lmbda
   - For your reference:
https://github.com/CERN/TIGRE/blob/c5d0050f5a87d5979524bbab9639d092266ea579/Python/tigre/algorithms/iterative_recon_alg.py#L127-L134

- I think that it would be nice to add a note that lmbda is not a typo.
   - or change the option name to step_size , for example.
   - or other...
   - but this is another issue.

### CODE REVIEW

**Comment by AnderBiguri** [comment]
lambda reduction is not a step size, lambda itself is. Reduction is by how much it is slowed down. Maybe lamdba is not a very ovbious name I guess, but its generally called that in maths papers. What do you think?

**Comment by genusn** [comment]
A happy new year.

Thank you for your comments and merging my PRs.

Hmm.... The first book that I read was Kak and Slaney's book (http://www.slaney.org/pct/pct-toc.html, p.284), and it uses 'relaxation parameter' $\alpha$. It cited Herman's pager, which seems to use $\lambda$.
Wiki (https://en.wikipedia.org/wiki/Gradient_descent) uses $\gamma$ for 'step size'.
Furthermore, in python, ```lmbda```, ```lmbda_red``` and ```tvlambda``` are correct, not ```lambda``` , ```lambda_red``` and ```tvlmbda``` respectively.

I think it is Okay to use alpha, beta, gamma, A, b, x, etc. inside the toolbox, but I don't think it's user-friendly to expose them.
However,  ```lambda``` is used both in MATLAB and Python from the beginning. I think it is difficult to change its name, but additional explanation such as 

```lmbda``` is the relaxation parameter if you use the default ```dataminimizing```, which is GD. Note that the parameter name is lmbda, not lambda because the word ```lambda``` is reserved by Python :-P

, for example of course, might be a possible solution.

**Comment by AnderBiguri** [comment]
Happy new year to you too!

Indeed I did not  think in the future when assigning the name `lambda` in the MATLAB version hehe. 

I agree too, that many of the parameters have terrible names. I still don't know how to tackle the enormous list of TV parameters with random greek letters.  I was thinking on making some aliases, but I think it makes the code harder to maintain and uglier, so maybe we need to accept that the names are as they are. As you say, likely the best idea is to just add good explanations of what they are with other words, such as "step size" etc. 

This is also where the python demos are needed. I think that the MATLAB ones do a relatively good job in explaining these things in general.

**Comment by genusn** [comment]
Agree. #219 and #194 seem to be related to this discussion.

**Pull request merged**
