### PR TITLE
Python demos cleanup

### LINKED ISSUE #265: plotProj is unfinished in python
Currently there is a function `plotProj` in python that has no optional arguments, and a semi-finished class that has many optional arguments, but is still non-functional. 

I suggest finishing the class and using that.

### PR DESCRIPTION
**Pull request by AnderBiguri**
This PR will delete old demos and documents (as they are incomplete) and make new demo scripts that are equal to the matlab ones. 

Help appreciated, please do comment if you decide to translate a demo.

TODO:

- [x] d01_CreateGeometry.pu	   	       	      
- [x] d02_SampleData.py	  	       		      
- [x] d03_generateData.py	   	       		      
- [x] d04_SimpleReconstruction.py    	      
- [x] d05_plottingFunctions.py
- [x] Fix #265            	      
- [x] d06_Algorithms01.py	      
- [x] d07_Algorithms02.py
- [x] d08_Algorithms03.py
- [x] d09_Algorithms04.py
- [x] d10_QualityMeasurements.py
- [ ] d11_PostProcessing.py 
- [x] d12_ProjectionOperators.py
- [x] d13_HelicalGeometry.py
- [x] d14_Offsets.py
- [x] d15_3Dparallel.py
- [x] d16_2Dtomography.py
- [x] d17_DetectorRotation.py
- [x] d18_ArbitraryAxisOfRotation.py
- [ ] d19_DBTexample.py
- [x] d20_Algorithms05.py
- [x] d21_ScannerDataLoader.py
- [x] d22_ListGPUs.py

### CODE REVIEW

**Comment by genusn** [comment]
As for the counterpart of `d22_ListGPUs.m`, please use `Python/tests/list_gpus.py` .

It seems that `add_ct_noise.py` is a bottle neck. Have you already written it?

**Comment by AnderBiguri** [comment]
Yes indeed @genusn , I deleted many things, but I plan to reuse much of the code there. 
No, everything I've done will be pushed to this branch for visibility, so feel free to play with that. 

I myself will try to go demos one by one in order. 
Currently there is an issue with this branch that I am trying to solve: To save memory I changed the location of the `head.mat` to `Common` , and while this is good for MATLAB, its not for python, as the path to this file is not known after the `setup.py install`. I think there is a way to tell `setuptools` that you have data and to copy it to the install folder, but I haven't tested it yet. 
Will report back if I fix it, but meanwhile if you find a solution please let me know.

**Comment by genusn** [comment]
Rough sketch:
1. add empty `__init__.py` file under `demos` folder so that `find_packages()` can add `demos` directory to the `packages` option of  `setup`. (`demos` will be installed as a sibling of `tigre` folder.)
2.  add an option `data_files` to the `setup()` as
```
      data_files=[('demos', ['../Common/data/head.mat'])],
```
3. ```python setup.py install --user```
4. head.mat is installed at
```
"........\site-packages\pytigre-0.1.8-py3.8-win-amd64.egg\demos\head.mat"
```

BTW, the line of  `license_file` would be
```
      license_files=('LICENSE',),
```
or 
```
      license_files=('../LICENSE.txt',),
```

**Comment by AnderBiguri** [comment]
OK, done, that should work.

**Comment by AnderBiguri** [comment]
> It seems that `add_ct_noise.py` is a bottle neck. Have you already written it?

Done.

**Comment by genusn** [comment]
@AnderBiguri , 
Running `d03_...` on Python 3.8.5 + matplotlib 3.3.2, it said
```
.....python\tigre\utilities\plotproj.py:106: MatplotlibDeprecationWarning: The 'cmap' parameter to Colorbar has no effect because it is overridden by the mappable; it is deprecated since 3.3 and will be removed two minor releases later.
  fig.colorbar(mappable, cax=cax,cmap=self.colormap)
```

I modified `d03_...` to `tigre.plotproj(projections, colormap="plasma")`  and  compared the result of with and without `,cmap=self.colormap`, they looked the same.

**Comment by genusn** [comment]
@AnderBiguri Please find e8000779a4cdef827ecc85414f4b5522278a3b9d

**Comment by AnderBiguri** [comment]
@genusn  thanks for the heads up. I was testing all this in an older version of python. merged your commit.

**Comment by AnderBiguri** [comment]
Demo 11 requires #270 and #271 to get fixed.

**Comment by AnderBiguri** [comment]
#274 also needs fixing for this PR.

**Comment by AnderBiguri** [comment]
demo 9 needs #277 fixed. 

This is an important bug in general.

**Comment by AnderBiguri** [comment]
I will probably merge this without d11 and d19, leave them open for later fixing .

**Pull request merged**
