### PR TITLE
Issue410: Added groundtruth comparion flags to ./python/TIGRE/algorithms

### PR DESCRIPTION
**Pull request by ameyakhot**
Submitting my first every PR. Please be free to share feedback if there was anything that needs to be fixed. Thank you for the opportunity.

email: ameyakhot18@gmail.com

### CODE REVIEW

**Comment by AnderBiguri** [comment]
Thanks @ameyakhot !

This is a good step towards fixing the issue, but perhaps the issue wasn't clear enough, my bad!

This helps start with it, but now we need to do something with that groundtruth :) 

This is related to the `Quameasopts` variable, that sets the quality measures options.  As it is now, each iteration will check the quality measures against the previous iteration. The idea of adding a groundtruth is that when this is given (not otherwise), the quality measures should be compared against the groundtruth, instead of comparing them against the previous iteration.

**Comment by ameyakhot** [comment]
I see. So for every iteration, if the `Quameasopts` variable needs to be compared to groundtruth (if given else None). What actions should be taken if they `Quameasopts` is equal to groundtruth? Can you share some details? 

Thank you for your support.

**Comment by AnderBiguri** [comment]
hi @ameyakhot , no not the `Quameasopts` that is the options variable that is used to control that. 

I would suggest having a quick look on how this variable is used in the code. You can also check the MATLAB code (e.g. SART.m) to see how MATLAB handles this.

**Comment by ameyakhot** [comment]
Thank you for the explanation @AnderBiguri . I'll take a look for sure at the matlab and see how it works and try to understand what needs to be done in here.

**Comment by AnderBiguri** [comment]
Closing because this seems stale, feel free to reopen if you decide to keep working on it.

**Pull request closed without merging**
