### PR TITLE
Python MLEM

### PR DESCRIPTION
**Pull request by genusn**
I ported MLEM.m to Python because I wanted to try this algorithm on Python.

## Test code
```
#%%
import numpy as np
import sys
from matplotlib import pyplot as plt

import tigre
import tigre.algorithms as algs
from tigre.demos.Test_data import data_loader

#%%
test_anisotropic_case = False#True
if test_anisotropic_case:
    nangles=30
    nVoxelX=256
    nVoxelY=128
    nVoxelZ=64
    nDetectorU=250
    nDetectorV=300#125
else:
    nangles=100
    nVoxelX=256
    nVoxelY=256
    nVoxelZ=256
    nDetectorU=256
    nDetectorV=256

geo=tigre.geometry(mode='cone', nVoxel=np.array([nVoxelZ,nVoxelY,nVoxelX]), default=True)
geo.nDetector=np.array([nDetectorV, nDetectorU])
geo.dDetector=np.array([0.8, 0.8])*3
geo.sDetector=geo.nDetector *geo.dDetector

niter = 3
angles = np.linspace(0, 2 * np.pi, nangles, endpoint=False, dtype=np.float32)
head = data_loader.load_head_phantom(geo.nVoxel)
proj = tigre.Ax(head,geo,angles)
#%%
out=[]
out.append({"alg":"FDK"   , "img":algs.fdk(proj,geo,angles)})
out.append({"alg":"OSSART", "img":algs.ossart(proj,geo,angles,niter,blocksize=20)})
out.append({"alg":"MLEM"  , "img":algs.mlem(proj,geo,angles,niter)})
#%%
list_idxZ = [0, geo.nVoxel[0]*1//4, geo.nVoxel[0]*2//4, geo.nVoxel[0]*3//4, geo.nVoxel[0]-1]
fig, axes = plt.subplots(len(list_idxZ)+2,len(out), figsize=(8,6))
for idx, idxZ in enumerate(list_idxZ):
    for idx_out, output in enumerate(out):
        axis = axes[idx, idx_out]
        if idx==0:
            axis.set_title(output["alg"])
        mappable = axis.imshow(output["img"][idxZ])
        fig.colorbar(mappable, ax = axis)
for idx_out, output in enumerate(out):
    axis = axes[len(list_idxZ), idx_out]
    mappable = axis.imshow(np.squeeze(output["img"][:,nVoxelY//2,:]))
    fig.colorbar(mappable, ax = axis)
for idx_out, output in enumerate(out):
    axis = axes[len(list_idxZ)+1, idx_out]
    mappable = axis.imshow(np.squeeze(output["img"][:,:,nVoxelX//2]))
    fig.colorbar(mappable, ax = axis)

fig.savefig("mlem_aniso_vol.png" if test_anisotropic_case else "mlem_iso_vol.png"  )
plt.show()
```
## Results

mlem_aniso_vol
mlem_iso_vol

## Test environment
| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10 |
|**Python(anaconda)**|  3.7.7 |
|**CUDA**| 10.1|
|**Visual Studio**| 2019 |
|**GPU**| GTX1060 |

### CODE REVIEW

**Comment by yliu88au** [comment]
Good, I also did the porting of MLEM in my branch: yliu88au\TIGRE.

**Comment by AnderBiguri** [comment]
@yliu88au @genusn  I had some time booked today to port Yi's MLEM to python today, but seems that you are saving me time! 
Apologies for not porting it sooner and make you both repeat work!

**Comment by AnderBiguri** [comment]
I am actually quite surprised that OS-SART does worse than MLEM. I need to test this in MATLAB too, I may be wrong, but would have expect MLEM to do much worse.

**Comment by yliu88au** [comment]
Please have a  look at my branch, I tried to tidy up most algorithms in MATLAB to make them more consistent. @AnderBiguri

**Comment by AnderBiguri** [comment]
@yliu88au I can only see modifications to python. Can you make a PR, so its easier for me to compare between CERN/TIGRE and yours?

**Comment by yliu88au** [comment]
@AnderBiguri If you use FDK result as the initial condition for OS-SART, it will be better. Besides, I am new to github, so I am not so sure on many operation yet.

**Comment by AnderBiguri** [comment]
@genusn  have a look at  PR #206 . Its quite wide, but there is a section for MLEM. Seems that @yliu88au has tidied the MATLAB code for MLEM and ported that nicely to python. Maybe that version is better? 

I will compare them myself, but if you are willing to have a look at both, it would be great as you wrote one of them, so you may be able to have a better insight than I have.

**Comment by genusn** [comment]
@AnderBiguri , @yliu88au , I only looked at statistical_algorithms.py, but it seems to be perfect; it is written in the same manner of other algorithms for python. The result of the test code above for anisotropic case is also OK. @AnderBiguri Please use Yi's version.

**Comment by AnderBiguri** [comment]
PR substituted by PR #206

**Pull request closed without merging**
