### PR TITLE
float precision fix for issue #544

### PR DESCRIPTION
**Pull request by simonCtBern**
Changed the function computeDeltasCube() in voxel_backprojection.cu to double precision, including double precision versions of coordinate rotation functions. Added a double precision Point3Ddouble struct to types_TIGRE.hpp. Integrated the computeDeltas_Siddon() function in Siddon_projection.cu from [IbexInnovations](https://github.com/IbexInnovations/TIGRE/blob/8d8c8eb4e7be922a69512baa08b4dad5bf516cc3/Common/CUDA/Siddon_projection.cu#L680) related to issue https://github.com/CERN/TIGRE/issues/355.

### CODE REVIEW

**Comment by AnderBiguri** [comment]
Thanks a lot!
I think this would also need to be propagated to at least `voxel_backprojection2.cu`. Are you happy to do it or should I do it?

**Comment by simonCtBern** [comment]
Yes I wanted to comment that I only copied the changes to voxel_backprojection2.cu, but I don't know where this function is called, so I couldn't test it. 
Also, I simply copied the coordinate rotation functions to voxel_backprojection2.cu since I don't really know the structure of the code, so they are defined identically in 2 places now. You'll probably want to clean this up...

**Comment by AnderBiguri** [comment]
hi @simonCtBern , I have done a commit to this PR, do you mind double checking the code for sanity? Just run whatever experiment this was fixing, just to make sure I haven't broken it :) 
Otherwise it runs on my PC locally with the same behaviour as before my commit.

**Comment by simonCtBern** [comment]
@AnderBiguri Looks good, the inaccuracy is still gone after pulling and recompiling.

**Pull request merged**
