### PR TITLE
iterative_recon_alg: switch l2l to numpy array

### PR DESCRIPTION
**Pull request by Scriptkiddi**
#308

### CODE REVIEW

**Comment by AnderBiguri** [comment]
Thanks! Will test and merge :)

**Comment by AnderBiguri** [comment]
Sorry for the delay. 

I think it would make sense to change the following too: 

https://github.com/CERN/TIGRE/blob/ff50fede05ccfa41584bb47e81033adfd5492938/Python/tigre/algorithms/iterative_recon_alg.py#L212

Would you mind doing and testing that?

**Comment by Scriptkiddi** [comment]
I'm sorry but I can not follow, did you link to the correct commit? If you mean the change I did, I have tested it.

**Comment by AnderBiguri** [comment]
@Scriptkiddi yes, you made this change:

https://github.com/CERN/TIGRE/blob/ff50fede05ccfa41584bb47e81033adfd5492938/Python/tigre/algorithms/iterative_recon_alg.py#L213

and I was suggesting that the previous line 

https://github.com/CERN/TIGRE/blob/ff50fede05ccfa41584bb47e81033adfd5492938/Python/tigre/algorithms/iterative_recon_alg.py#L212

May require the exact same change, and if you were willing to change and test it out :)

**Comment by Scriptkiddi** [comment]
Ah got it will go and check

**Comment by Scriptkiddi** [comment]
Fixed it, all other list initialization seem to be ok

**Comment by AnderBiguri** [comment]
Thanks for the help and the work! I will test and merge!

**Pull request merged**
