### PR TITLE
Axis-parallel rays issue in Siddon

### PR DESCRIPTION
**Pull request by AnderBiguri**
This seems to solve it. 

- [x] more testing
- [x] Evaluate computational cost of the addition

### CODE REVIEW

**Comment by AnderBiguri** [comment]
Seems to work well at odd detector and `angles=[0,pi/2,pi,3/2*pi]`

**Comment by AnderBiguri** [comment]
Seems that its faster now that it was before, by around 4%. 

Confusing. Maybe checking all the `if` condition and failing them all (see [here](https://github.com/CERN/TIGRE/issues/207#issuecomment-741728041)) takes longer due to branching.

**Comment by AnderBiguri** [comment]
This still does not work. There is a case that I found that I still don't understand:
```

%% Init 
clear;
close all;
%% Test parameters
test_case = 1

if test_case == 0
    % Both even
    nVoxelZ=10;
    nDetectorV=10;
elseif test_case == 1
    % nVoxel Even, nDetec Odd
    nVoxelZ=10;
    nDetectorV=11;
elseif test_case == 2
    % nVoxel Odd, nDetec Even
    nVoxelZ=11;
    nDetectorV=10;
else
    % nVoxel Odd, nDetec Odd
    nVoxelZ=11;
    nDetectorV=11;
end

nVoxelX = nVoxelZ;
nVoxelY = nVoxelZ;
nDetectorU = nDetectorV;

nangles=10;

mode='cone';  % 'parallel'
ptype= 'Siddon'; % 'interpolated' % 'ray-voxel'
%%
geo=defaultGeometry('mode',mode);
geo.DSD = 2000;
geo.DSO = 1000;
geo.nVoxel = [nVoxelX;nVoxelY;1];
geo.dVoxel = [1.0; 1.0; 1.0];
geo.sVoxel = geo.nVoxel .* geo.dVoxel;
geo.dDetector = [2;2] ;              % size of each pixel            (mm)
geo.nDetector = [nDetectorU; 1];     % has to be true 3D for python version
geo.sDetector = geo.dDetector .* geo.nDetector;
geo.offOrigin = [0;0;0];
geo.offDetector = -[0.,0.]' ;
geo.rotDetector = [0; 0; 0];
geo.accuracy=0.01;

%%
angles = linspace(0, 2 * pi - 2*pi/nangles, nangles);

dot = zeros(geo.nVoxel', 'single');
dot(int32((geo.nVoxel(1))/2):int32((geo.nVoxel(1)+1)/2), int32((geo.nVoxel(2))/2):int32((geo.nVoxel(2)+1)/2), int32((geo.nVoxel(3))/2)) = 1;
%%

proj = Ax(dot,geo,angles, ptype);
plotProj(proj, angles,'slice',6)
proj(:,:,6)

```

this will print 
`         0         0         0         0    0.9997         0    1.0002         0         0         0         0`
which makes no sense (there is a small tilt because the angle is not numerically exactly pi, but the middle zero makes no sense. 

If instead we use 
`dot = ones(geo.nVoxel', 'single');`
then it will print
`    4.9999   10.0002   10.0002   10.0002   10.0002   10.0002   10.0002   10.0002   10.0002   10.0002    5.0001`

The first test seem to suggest that the forward projector is missing an entire pixel in one ray (but not in the adjacent rays!). This suggest numerical issues computing that ray. However, the second test suddenly takes into account that voxel, otherwise the middle number would be missing around `1` unit in value (e.g. it would be `9.00002`)

So what the heck is going on.

**Comment by AnderBiguri** [comment]
Interestingly the above only happens in this very particular geometry, any eps out of that fixes it...

**Comment by genusn** [comment]
> Interestingly the above only happens in this very particular geometry

I also observed it. Under investigation...

**Comment by AnderBiguri** [comment]
> > Interestingly the above only happens in this very particular geometry
> 
> I also observed it. Under investigation...

My current stage:

I see that the intersection with the `y` axis:https://github.com/CERN/TIGRE/blob/f86e18ab27aa9cb0c2d179a08552b54cd471748d/MATLAB/Source/Siddon_projection.cu#L242
happens much earlier for that pixel. Backtracking numerically on why....

**Comment by AnderBiguri** [comment]
Ah, I think its a numerical precision error.

I tracked numerically the issue. We are talking about a pixel that is essentially at a axis-parallel direction, but just offseted by an incredibly small mount, due to angle being almost `pi`, but not fully `pi`. 

So, in theory, `ay=Inf` (first intersection with the `y` face of voxels). Note that I removed the eps in the denominator. 

https://github.com/CERN/TIGRE/blob/f86e18ab27aa9cb0c2d179a08552b54cd471748d/MATLAB/Source/Siddon_projection.cu#L205

For that pixel, `jmin-source.y` is `8.72612e-05` and `0.0001749992`. This shoudl be `0/0` but its not. This division precision is not good enough thus the result is a bit skewed, enough to generate a low number for `ay` (`0.4986`) and screw the line integral. Ugh.

**Comment by AnderBiguri** [comment]
OK, I think this one fixes it, but I am still worried that it will kick in some other situation....

I have tested it with minimal changes to geometry, and it seems that even very small changes to `geo` generate measurable changes in the projection (i.e. this latest commit only suppresses very very very small numerical non-zero issues) and I can't seem to reproduce/find a pixel that will not be computed. I

I will leave this open for a bit, as I need to test more systematically.

**Comment by AnderBiguri** [comment]
Resolve #208, Resolve #207

**Comment by AnderBiguri** [comment]
@yliu88au Hi there! 

I am writing this on the pull request #218 in TIGRE (so even if you get an email, this is a public post on this particular topic). 
I was wondering if you could test this branch of TIGRE (https://github.com/CERN/TIGRE/tree/axis-parallel) as I think I solved the 2D tomography issues here. In my tests, all works well, and you definitely do not need the `0.5` in the `geo.offDetector`,  it can be (shoudl be!) all zeroes. 

As you seem to be doing 2D tomography, I though of you as the best person to test this! 
(My various test worked well, but its always good to have someone else test).

**Comment by genusn** [comment]
Ignored 0.001 corresponds to 0.001/SID radians. It's negligible, of course. :-)

**Comment by AnderBiguri** [comment]
@genusn ah, yes, its its negligible for humans, my only worry is for this to cause some other numerical issue in some other edge-case.... But yeah, for now I can't really think of anything wrong happening with this micro-error that I introduce here....

**Pull request merged**
