### PR TITLE
Optimized proton radiographies for pCT image reconstruction

### PR DESCRIPTION
**Pull request by skaser**

### CODE REVIEW

**Comment by AnderBiguri** [comment]
Thanks a lot! Can I do commits/change things of the code?

**Comment by skaser** [comment]
Thanks for your support! And of course you can do that!

**Comment by AnderBiguri** [comment]
@skaser  I will slowly start  having a look at this in more detail again. 

Could you change 1 thing for me: It makes sense for only to have 1 compile script. Can you merge the two that you have?

**Review by AnderBiguri — APPROVED** [review]
Great!

This is good to go I'd say!
I will try to make a note of things to improve programatically, but the most important thing is there: it works, and it works quite well! 

Congrats on the good job!

**Pull request merged**
